"""Corpus tables: documents, chunks, and ingestion runs.

Two modelling choices carry most of the weight here.

**A document is `(source_path, version)`, not a file.** The same page exists in
every release branch, and the whole point of the project is to keep those
copies distinguishable. `is_latest_for_path` marks the newest indexed version of
each page so "answer from latest" is an indexed lookup rather than a sort.

**A chunk belongs to a chunker, not just a document.** `chunker_name` carries
the strategy *and* its parameters (`fixed-512-64`), so several chunkings of the
same corpus coexist and a chunking experiment is a config change rather than a
re-ingestion. Every retrieval query filters on it.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    BigInteger,
    Computed,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

# bge-small-en-v1.5. A different embedding model means a migration, which is the
# honest cost of storing vectors in a typed column.
EMBEDDING_DIM = 384


class Document(Base):
    """One documentation page, in one release version."""

    __tablename__ = "documents"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    source_path: Mapped[str] = mapped_column(String(1024), nullable=False)
    version: Mapped[str] = mapped_column(String(16), nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False, default="")
    url: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # SHA-256 of normalized content. Ingestion compares this to decide whether a
    # page needs re-parsing and re-embedding; equal hash means skip entirely.
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)

    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    is_latest_for_path: Mapped[bool] = mapped_column(nullable=False, default=False)
    # Set when a page disappears from a branch. Kept rather than deleted so an
    # old trace still resolves its citations.
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)

    meta: Mapped[dict[str, Any]] = mapped_column("metadata", JSONB, nullable=False, default=dict)

    chunks: Mapped[list[Chunk]] = relationship(
        back_populates="document", cascade="all, delete-orphan", passive_deletes=True
    )

    __table_args__ = (
        UniqueConstraint("source_path", "version", name="uq_documents_source_path_version"),
        Index("ix_documents_version", "version"),
        Index("ix_documents_source_path", "source_path"),
        Index("ix_documents_latest", "source_path", "is_latest_for_path"),
    )

    def __repr__(self) -> str:
        return f"<Document {self.source_path}@{self.version}>"


class Chunk(Base):
    """A retrievable span of one document, under one chunking strategy."""

    __tablename__ = "chunks"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    document_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False
    )

    # Denormalized from `documents` so the version pre-filter never needs a join.
    # Retrieval runs this filter on every query; the duplication is worth it.
    version: Mapped[str] = mapped_column(String(16), nullable=False)
    chunker_name: Mapped[str] = mapped_column(String(64), nullable=False)

    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)

    # "Pods > Pod Lifecycle > Container probes". Doubles as stable gold evidence
    # in the eval set: it survives re-chunking, unlike a chunk id.
    heading_path: Mapped[str] = mapped_column(Text, nullable=False, default="")
    chunk_type: Mapped[str] = mapped_column(String(16), nullable=False, default="prose")
    token_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM), nullable=True)

    # Generated by Postgres, so it can never drift from `text`.
    tsv: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('english', text)", persisted=True),
        nullable=True,
    )

    meta: Mapped[dict[str, Any]] = mapped_column("metadata", JSONB, nullable=False, default=dict)

    document: Mapped[Document] = relationship(back_populates="chunks")

    __table_args__ = (
        UniqueConstraint(
            "document_id", "chunker_name", "chunk_index", name="uq_chunks_doc_chunker_index"
        ),
        Index("ix_chunks_version_chunker", "version", "chunker_name"),
        Index("ix_chunks_document", "document_id"),
        # HNSW and GIN indexes are created in the migration: SQLAlchemy cannot
        # express pgvector operator classes, and Alembic cannot reflect them.
    )

    def __repr__(self) -> str:
        return f"<Chunk {self.id} {self.heading_path[:40]!r}>"


class IngestionRun(Base):
    """One ingestion invocation and what it changed.

    The counts are the acceptance criterion for Phase 1: a re-run over an
    unchanged corpus must report `embedded == 0`.
    """

    __tablename__ = "ingestion_runs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    config_name: Mapped[str] = mapped_column(String(128), nullable=False)
    config_hash: Mapped[str] = mapped_column(String(32), nullable=False)
    chunker_name: Mapped[str] = mapped_column(String(64), nullable=False)
    versions: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)

    documents_added: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    documents_updated: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    documents_unchanged: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    documents_deleted: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    chunks_written: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    chunks_embedded: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    duration_seconds: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    meta: Mapped[dict[str, Any]] = mapped_column("metadata", JSONB, nullable=False, default=dict)

    def __repr__(self) -> str:
        return (
            f"<IngestionRun {self.id} +{self.documents_added} ~{self.documents_updated} "
            f"={self.documents_unchanged}>"
        )
