"""Create documents, chunks, and ingestion_runs.

Hand-written rather than autogenerated, because three things in this schema are
outside what Alembic can express or reflect:

* the `tsv` generated column,
* the HNSW index with pgvector's `vector_cosine_ops` operator class,
* the GIN index over `tsv`.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 384


def upgrade() -> None:
    op.create_table(
        "documents",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_path", sa.String(length=1024), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("is_latest_for_path", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_documents"),
        sa.UniqueConstraint("source_path", "version", name="uq_documents_source_path_version"),
    )
    op.create_index("ix_documents_version", "documents", ["version"])
    op.create_index("ix_documents_source_path", "documents", ["source_path"])
    op.create_index("ix_documents_latest", "documents", ["source_path", "is_latest_for_path"])

    op.create_table(
        "chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column("chunker_name", sa.String(length=64), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("heading_path", sa.Text(), nullable=False),
        sa.Column("chunk_type", sa.String(length=16), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=True,
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name="fk_chunks_document_id_documents",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_chunks"),
        sa.UniqueConstraint(
            "document_id", "chunker_name", "chunk_index", name="uq_chunks_doc_chunker_index"
        ),
    )
    op.create_index("ix_chunks_version_chunker", "chunks", ["version", "chunker_name"])
    op.create_index("ix_chunks_document", "chunks", ["document_id"])

    # Lexical retrieval (Phase 3) ranks with ts_rank_cd over this index.
    op.create_index(
        "ix_chunks_tsv_gin", "chunks", ["tsv"], postgresql_using="gin"
    )

    # Dense retrieval. HNSW over cosine distance: `m` and `ef_construction` are
    # pgvector's defaults, which are a reasonable build-time/recall trade-off
    # for a corpus of this size. The index name ends in `_hnsw` so
    # migrations/env.py excludes it from autogenerate.
    op.execute(
        "CREATE INDEX ix_chunks_embedding_hnsw ON chunks "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )

    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("config_name", sa.String(length=128), nullable=False),
        sa.Column("config_hash", sa.String(length=32), nullable=False),
        sa.Column("chunker_name", sa.String(length=64), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("documents_added", sa.Integer(), nullable=False),
        sa.Column("documents_updated", sa.Integer(), nullable=False),
        sa.Column("documents_unchanged", sa.Integer(), nullable=False),
        sa.Column("documents_deleted", sa.Integer(), nullable=False),
        sa.Column("chunks_written", sa.Integer(), nullable=False),
        sa.Column("chunks_embedded", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_ingestion_runs"),
    )


def downgrade() -> None:
    op.drop_table("ingestion_runs")
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding_hnsw")
    op.drop_index("ix_chunks_tsv_gin", table_name="chunks")
    op.drop_index("ix_chunks_document", table_name="chunks")
    op.drop_index("ix_chunks_version_chunker", table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_documents_latest", table_name="documents")
    op.drop_index("ix_documents_source_path", table_name="documents")
    op.drop_index("ix_documents_version", table_name="documents")
    op.drop_table("documents")
